import type { GetServerSideProps, NextPage } from "next";
import { getSession, signIn } from "next-auth/react";
import Head from "next/head";
import { FcGoogle } from "react-icons/fc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mx-auto my-12">
        <div className="grid grid-cols-2">
          <div>
            <h1 className="font-bold font-head-bold text-7xl leading-tight">
              Phantom brings <span className="text-green-400">fun</span> and{" "}
              <span className="text-green-400">privacy</span> back to your
              conversation.
            </h1>
            <button
              className="bg-zinc-900 flex items-center gap-4 py-6 px-12 rounded-md mt-8 text-xl"
              onClick={() => signIn("google")}
            >
              <FcGoogle /> Sign in with Google
            </button>
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getSession({
    ctx,
  });

  if (session) {
    return {
      redirect: {
        destination: "/app",
        permanent: true,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
